// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:cash_peak/data/models/expense.dart';
import 'package:cash_peak/data/models/income.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(IncomeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(IncomeAdapter());
  }
}
